#!/usr/bin/env node

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { execSync } from 'child_process';

// Get the current directory
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Get the project root directory (the parent of webview)
const projectRoot = path.resolve(__dirname, '../..');
const buildGradlePath = path.join(projectRoot, 'build.gradle');

// Read the build.gradle file
const buildGradleContent = fs.readFileSync(buildGradlePath, 'utf8');

// Extract the version number
// Look for a line like: version = '0.1.0-beta3'
let versionMatch = buildGradleContent.match(/^version\s*=\s*'(.+)'$/m);
if (!versionMatch) {
  // If the regex above fails, try a fallback approach
  const lines = buildGradleContent.split('\n');
  const versionLine = lines.find(line => line.trim().startsWith('version ='));
  if (versionLine) {
    const match = versionLine.match(/version\s*=\s*'(.+)'/);
    if (match) {
      versionMatch = match;
    }
  }
}
if (!versionMatch) {
  console.error('Error: Could not find version in build.gradle');
  process.exit(1);
}

const version = versionMatch[1];
console.log(`Found version: ${version}`);

const readGitValue = (command) => {
  try {
    return execSync(command, { cwd: projectRoot, encoding: 'utf8', stdio: ['ignore', 'pipe', 'ignore'] }).trim() || 'unknown';
  } catch {
    return 'unknown';
  }
};

const gitCommit = readGitValue('git rev-parse --short=12 HEAD');
const gitBranch = readGitValue('git rev-parse --abbrev-ref HEAD');
const buildTime = new Date().toISOString();
const webviewBundleSha256Placeholder = '__CC_GUI_WEBVIEW_BUNDLE_SHA256__';

// Create the version file for the webview
const versionDir = path.join(__dirname, '../src/version');
if (!fs.existsSync(versionDir)) {
  fs.mkdirSync(versionDir, { recursive: true });
}

const versionFilePath = path.join(versionDir, 'version.ts');
const versionFileContent = `// Auto-generated version file
// This file is automatically generated during the build process
// Do not edit manually

export const APP_VERSION = '${version}';
export const APP_GIT_COMMIT = '${gitCommit}';
export const APP_GIT_BRANCH = '${gitBranch}';
export const APP_BUILD_TIME = '${buildTime}';
export const APP_WEBVIEW_BUNDLE_SHA256 = '${webviewBundleSha256Placeholder}';
`;

fs.writeFileSync(versionFilePath, versionFileContent);
console.log(`Version file created at: ${versionFilePath}`);
